FROM python:3.11
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src/

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0"]